### ISSUE TITLE
Review how to better display and establish a pattern for long pages 

### ISSUE THREAD

**Issue by pcambra** [Cambrico/farm_nfa#162]
(for example Agoro-Agu CFR: asset/523)

**Comment by yolandagoex** [comment]
A need has been identified to improve the pattern for heavy content pages. See [https://forests.nfa.go.ug/asset/523](https://forests.nfa.go.ug/asset/523)

In order to make our users more comfortable with heavy content pages, a solution based on the concept of progressive disclosure is presented. The component that better seems to fit with this concept is an accordion.

A proposal with an accordion can be explored here: [https://www.figma.com/file/tc9i4iTe9juuqr8J815IFW/Long-pages?node-id=1%3A42](https://www.figma.com/file/tc9i4iTe9juuqr8J815IFW/Long-pages?node-id=1%3A42)

**Comment by yolandagoex** [comment]
In this case we would need to know if the committee is happy with the re-design based on the accordion component in order to implement it.

**Comment by pcambra** [comment]
Just making sure @LeScruf sees this comment

**Comment by yolandagoex** [comment]
A new iteration based on the solution designed for issue #163 (vertical tabs) has been created after @LeScruf comment on Figma: https://www.figma.com/file/WIWQyXB9nikWwPuKahEfxi/Iteration-long-pages?node-id=0%3A1

**Comment by pcambra** [comment]
We need to show the maps/images with a label "Maps" on the top of the vertical tabs.

The images need to be collapsed, or maybe first one visible, in an accordion-like structure.

**Comment by yolandagoex** [comment]
A second iteration over the long pages design with the latest suggestions can be seen here @LeScruf: https://www.figma.com/file/piSrp57wzXg8GLTnM8VaRn/Second-iteration-long-pages

**Comment by ygoex** [comment]
Closing this one after @LeScruf gave us green light to start implementing it. We'll now focus on #192
