### ISSUE TITLE
Review how to improve the UX on very long forms

### ISSUE THREAD

**Issue by pcambra** [Cambrico/farm_nfa#164]
For example the Add CFR one

**Comment by yolandagoex** [comment]
A need has been identified to improve the pattern for long forms. See https://forests.nfa.go.ug/asset/add/cfr

In order to make our users more comfortable with long forms, a solution based on the concept of progressive disclosure is presented. The component that better seems to fit with this concept is a multi step form a.k.a wizard.

A proposal with a multi step form can be explored here: https://www.figma.com/file/TknVBoMX7vWxnhAvIbRGHC/Long-forms?node-id=0%3A1

**Comment by yolandagoex** [comment]
In this case we would need to know which fields are going to continue after the UX/UI reorganisation, and which ones are no longer needed.

**Comment by pcambra** [comment]
Just making sure @LeScruf sees this comment

**Comment by ygoex** [comment]
Closing this one after @LeScruf gave us green light to start implementing it. We'll now focus on https://github.com/Cambrico/farm_nfa/issues/193
