### ISSUE TITLE
Search/filter area list

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#6]
> The list of areas should be collapsable and also filterable and searchable

The area list (/farm/areas) is currently a View, so we might be able to use exposed filters for it.

Questions:

- Search/filter by name?
- Area type
- others?

**Comment by mstenta** [comment]
I wonder: does this need to be done on /farm/areas? Or would it be more useful to think about adding filters to the dashboard, where we are hoping to funnel users into "Plans"?

**Comment by LeScruf** [comment]
To be difficult - we need both - because users will be accessing the system for different reasons - sometimes to use the planning tool, sometimes to check out what the status of a boundary or compartmentalization of a reserve is - as a quick look. We want to have the system be both a quick reference tool as well as more detailed management tool.

**Comment by mstenta** [comment]
Thanks! Makes sense.

For future reference, the two paths we are discussing are:

- https://nfa.farmos.net/farm/areas (View Tree of area terms)
- https://nfa.farmos.net/ (dashboard panes)
